# Generated by Django 3.1.7 on 2021-03-06 20:20

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210306_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'All Series'},
        ),
        migrations.RemoveField(
            model_name='bookpage',
            name='series',
        ),
        migrations.AddField(
            model_name='bookpage',
            name='series',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='books.Series'),
        ),
    ]
