# Generated by Django 3.1.7 on 2021-03-07 17:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('books', '0005_auto_20210307_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorpage',
            old_name='name',
            new_name='author_pen_name',
        ),
        migrations.AddField(
            model_name='authorpage',
            name='author_bio',
            field=wagtail.core.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authorpage',
            name='author_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
