# Generated by Django 3.1.7 on 2021-03-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_remove_genre_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='name',
        ),
    ]
