# Generated by Django 3.1.7 on 2021-03-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20210307_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
