# Generated by Django 3.1.7 on 2021-03-07 20:07

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('books', '0015_auto_20210307_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpage',
            name='author',
            field=models.ForeignKey(blank=True, help_text="Choose one of your Author Pages to assign a pen name to this book. \n        If you don't see the pen name you want, you might need to set up a new AuthorPage \n        for that pen name!", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='book_title',
            field=models.CharField(help_text='The exact title of the book. It will \n    be saved in this format in the database to display on related pages.', max_length=200),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='content_warnings',
            field=models.ManyToManyField(blank=True, help_text='(Optional):\n    Choose one or more content warnings for this book. If you don\'t see the warning you want listed here,\n    click "Add Content Warnings on the menu on the left and add in your warnings.', to='books.ContentWarning'),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='A description of your book.', null=True),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Optional: Choose one or more\n    genres for this book. If you don\'t see the genre you need, click "Add Genre to List" from the menu\n    on the left and add in your genre.', to='books.Genre'),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='other_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='This is an optional field. Text\n    added and formatted here will appear close to the bottom of the book page, right above the section\n    for content warnings.', null=True),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='release_date',
            field=models.DateField(blank=True, help_text='The book release date. This\n    field is optional.', null=True),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='series',
            field=models.ForeignKey(blank=True, help_text="Choose a series page to assign this book to a Series. If you don't see\n        the series you want, you might need to set up a new Series Page.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
