# Generated by Django 3.1.7 on 2021-03-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_auto_20210307_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpage',
            name='sort_order',
            field=models.IntegerField(blank=True, help_text='This field is optional, but if filled in,\n    it lets you pick where this book shows up in the "all books" section of your website. The higher the number, the \n    closer to the top of the page the book will be.', null=True),
        ),
    ]
