# Generated by Django 3.1.7 on 2021-03-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_bookpage_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpage',
            name='teaser',
            field=models.TextField(blank=True, help_text='A brief teaser description of your \n    book. This is the paragraph that will show up on the "all books" page.', null=True),
        ),
    ]
