# Generated by Django 3.1.7 on 2021-03-02 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210302_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='intro',
            new_name='teaser',
        ),
    ]
