# Generated by Django 3.1.7 on 2021-03-07 19:08

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210307_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='caption_text',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
